name: maternal_triage
description: Explainable AI-Based Maternal Triage Decision-Support System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  onnxruntime: ^1.4.1
  fl_chart: ^0.66.2
  go_router: ^13.0.1
  connectivity_plus: ^5.0.2
  toastification: ^3.0.3
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  flutter_hooks: ^0.21.3+1
  equatable: ^2.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  formz: ^0.8.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.12.2
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/shap/
    - assets/scaler/
