// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8o8Dn7V1RAeR7tik2wpTIyYtqAtPSl2g',
    appId: '1:101813985035:web:5569d04ccead8c392ccc0e',
    messagingSenderId: '101813985035',
    projectId: 'maternal-care-dce44',
    authDomain: 'maternal-care-dce44.firebaseapp.com',
    storageBucket: 'maternal-care-dce44.firebasestorage.app',
    measurementId: 'G-PLK696PY9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1yp_upiy3h8EfVeCe4U5mRs5KXO8hKI',
    appId: '1:101813985035:android:fe7fc548e089a0092ccc0e',
    messagingSenderId: '101813985035',
    projectId: 'maternal-care-dce44',
    storageBucket: 'maternal-care-dce44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj87S0CWzcbvRg1_MkecCnOcT6dXbYQM8',
    appId: '1:101813985035:ios:f7fb169ceab4c0252ccc0e',
    messagingSenderId: '101813985035',
    projectId: 'maternal-care-dce44',
    storageBucket: 'maternal-care-dce44.firebasestorage.app',
    androidClientId: '101813985035-u9achsiu9adqhh9k40050d5jsh5k8pql.apps.googleusercontent.com',
    iosClientId: '101813985035-gamun9b9tau29lc5mcg4junrtrip8d33.apps.googleusercontent.com',
    iosBundleId: 'com.maternaltriage.maternalTriage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj87S0CWzcbvRg1_MkecCnOcT6dXbYQM8',
    appId: '1:101813985035:ios:f7fb169ceab4c0252ccc0e',
    messagingSenderId: '101813985035',
    projectId: 'maternal-care-dce44',
    storageBucket: 'maternal-care-dce44.firebasestorage.app',
    androidClientId: '101813985035-u9achsiu9adqhh9k40050d5jsh5k8pql.apps.googleusercontent.com',
    iosClientId: '101813985035-gamun9b9tau29lc5mcg4junrtrip8d33.apps.googleusercontent.com',
    iosBundleId: 'com.maternaltriage.maternalTriage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8o8Dn7V1RAeR7tik2wpTIyYtqAtPSl2g',
    appId: '1:101813985035:web:a2cba26e795792e22ccc0e',
    messagingSenderId: '101813985035',
    projectId: 'maternal-care-dce44',
    authDomain: 'maternal-care-dce44.firebaseapp.com',
    storageBucket: 'maternal-care-dce44.firebasestorage.app',
    measurementId: 'G-MDN8WQ91CS',
  );

}